# Generated by Django 4.2.3 on 2023-11-02 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineBox',
            fields=[
                ('box_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'box',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoutineDetail',
            fields=[
                ('routine_detail_id', models.IntegerField(primary_key=True, serialize=False)),
                ('day', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'routinedetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('routine_id', models.AutoField(primary_key=True, serialize=False)),
                ('routine_name', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('routine_comment', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('recommend_count', models.IntegerField(blank=True, default=0, null=True)),
                ('routine_day', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nickname', models.ForeignKey(db_column='nickname', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='nickname')),
                ('recommend_user', models.ManyToManyField(related_name='recommend_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'routine',
            },
        ),
    ]
