# Generated by Django 4.2.3 on 2023-11-16 10:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='recommend_user',
            field=models.ManyToManyField(blank=True, related_name='recommend_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
