# Generated by Django 4.2.3 on 2023-11-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_alter_routine_recommend_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='routine_day',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='routine_name',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
