# Generated by Django 4.2.3 on 2023-08-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usebody',
            fields=[
                ('usebody_id', models.IntegerField(primary_key=True, serialize=False)),
                ('usebody_name', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'usebody',
                'db_table_comment': '부위 데이터',
                'managed': False,
            },
        ),
    ]
